apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: awscost-pet2cattle-https-cert
spec:
  commonName: awscost.pet2cattle.com
  dnsNames:
  - awscost.pet2cattle.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: awscost-pet2cattle-https-cert
